import type { Metadata } from "next"
import { GeistSans } from "geist/font/sans"
import { GeistMono } from "geist/font/mono"
import "./globals.css"
import Link from 'next/link'
import { Button } from '@/components/ui/button'

const geistSans = GeistSans
const geistMono = GeistMono

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} font-sans antialiased flex flex-col min-h-screen`}
      >
        <header className="border-b">
          <nav className="container flex h-16 items-center justify-between">
            <Link href="/" className="font-bold">
              Bill Buddy
            </Link>
            <Button asChild variant="ghost">
              <Link href="/login">Login</Link>
            </Button>
          </nav>
        </header>
        {children}
      </body>
    </html>
  )
}
